### ISSUE TITLE
BL2 Better Loot Mod not running (using GOTY edition) tried all the the different files independently or with the filtertool What can I do?

### ISSUE THREAD

**Issue by MeAndMySkyHooks** [BLCM/BLCMods#1001]

**Comment by apocalyptech** [comment]
If you're having problems running mods of any sort, I'd recommend checking out the Discord server in the #faq-read-me-before-asking section.  There's also a Google Doc which has most of that info: https://docs.google.com/document/d/17bwfQXWavBDiQuthxueXbRzB7LIx37Ki1a4-P-0qBW8/edit

**Comment by MeAndMySkyHooks** [comment]
Thanks for the link but my issue is that there is no apparent issue with including the mod or 'running' it, but  during gameplay there is no evidence of any loot changes in enemy drops or chests, also is it correct that the white dahl chests should have loot blue or higher?

**Comment by apocalyptech** [comment]
Could you give me a step-by-step of exactly what you're doing?

**Comment by MeAndMySkyHooks** [comment]
The UCP works fine, I had initially been using the weapon and enemy randomiser through the filtertool they worked fine. 
When adding the better loot mod using the filter tool no errors come up though when you open that folder all things contained are -hidden- (i don't know if that is what its supposed to do) 
I save the patch including better loot mod as the only additional mod in the filter tool. 
Open BL2 open existing game, save-quit, open console enter 'exec patch.txt' of as a standalone 'exec drops.txt' the 'enter'.
With the patch.txt the little description comes up, and the standalone shows nothing.
Enter game check vendor stores for rocket ammo - no rocket ammo, check dahl and red chests - usually green or white occasional blue.
this using the lootsplosion one.
Mods through filter tool are in 'mods' folder in 'binaries', standalones are just in 'binaries'

**Comment by apocalyptech** [comment]
Aha!  Okay, the problem is that you're executing more than one file.  When you import the mod into FilterTool and hit "Save", that'll save everything out to `patch.txt`, so that file now includes both UCP and Better Loot.  That's the *only* file that you should execute from the console.  When you execute the other file afterwards, it'll end up overwriting a bunch of stuff.  Basically: only ever execute the one single `patch.txt`.

Let me know if that clears it up for you!

**Comment by MeAndMySkyHooks** [comment]
Thanks for confirming the true extent of my retardation and dealing with me, you were right and i was dumb

**Comment by apocalyptech** [comment]
No worries!  That kind of thing's not always clear, and there's lots of advice still out there saying that it's okay to execute multiple mods from multiple files.  (Which used to be the case -- it's just that newer modding techniques have made it so that doesn't work anymore, a lot of the time.)

Glad you got it working!
