### ISSUE TITLE
How do i install randomizer mod ?

### ISSUE THREAD

**Issue by Heffox** [BLCM/BLCMods#1015]
ok, so to be honest i have never downloaded any mod for borderlands 2 before. But i have installed the filtertool and it seems to be working. But can someone please give me an easy step by step guide on how to install randomizers in filtertool ? Thank you so much <3

**Comment by apocalyptech** [comment]
Hello!  Since you asked this question, BLCMM has been released (which is FilterTool's replacement), and there's an area of the FAQ on our Discord which specifically talks about the randomizers.  If you're still having problems with the randomizer when using BLCMM, I'd recommend stopping over to the Discord and ask about it, since this "Issues" area on github isn't really very well monitored.
