### ISSUE TITLE
[REQUEST] better Grenades

### ISSUE THREAD

**Issue by TheJ5** [BLCM/BLCMods#1017]
We all now it, most parts for grenades are shit in this game. Therefore I thought it would be a cool mod that would remove Rubberized for example. Or make it that transfusion grenades only spawn in slag. Or make longbow more common and perhaps even reduce the fuse time.
Would be really glad if that was possible

**Comment by WubTheGame** [comment]
There's already a mod for removing the Rubberized prefix. I don't remember where though, you'd have to find it yourself.

**Comment by only801209** [comment]
Gpos

**Comment by apocalyptech** [comment]
Yeah, Jim Raven has a "RubberizedRemover" mod which will do that bit, at least.  As for the rest, it's all certainly possible, though I'm not aware of anything which does precisely that.

If this is something you're still interested in, I'd recommend checking out the Discord.  We're actually shutting down the "Issues" section here, since it's never been very well monitored.  You'll have a much quicker response time on the Discord.  See you there, perhaps!
