### ISSUE TITLE
TPS Better Loot Mod (Reasonable Drops) - UCP Compat How to change something? Glitch Loot

### ISSUE THREAD

**Issue by and1d** [BLCM/BLCMods#1040]
https://github.com/BLCM/BLCMods/blob/master/Pre%20Sequel%20Mods/Apocalyptech/TPS%20Better%20Loot%20Mod/TPS%20Better%20Loot%20Mod%20(Reasonable%20Drops)%20-%20UCP%20Compat.txt

Hi, I have some questions how i can change some things in this mod in Filter tool.

1: How can I change that in the normal game (not in DLC) no Glitch weapons drops from chests or from Enemys?                   In Vanilla they don´t drop in normal game or am i wrong?

2: Can i change it somehow that the better Moonstone chest option costs more moonstone, or that it not only drops legendary maybe some purple or so?

**Comment by apocalyptech** [comment]
Hey there - certainly anything's possible, though Better Loot doesn't have explicit options for toggling that stuff.

For point 1: With the current version of Better Loot (which is newer than the one when you originally posted this), you can edit "Drop Quality -> (whatever your quality is) -> Better Item Loot Pools -> Better Weapon Rarity Drops -> set GD_Itempools.WeaponPools.Pool_Weapons_All".  Find the stanza near the end which points at `GD_Ma_ItemPools.WeaponPools.Pool_Weapons_All_Glitch_Marigold` and set its `BaseValueConstant` or `BaseValueScaleConstant` to `0`.

For point 2: You can toggle the Moonstone improvements entirely by unchecking "Base Mod Configuration -> Better Containers -> Better Moonstone Chests".  That'll make sure they stay just like the vanilla game.  Altering the cost is certainly still possible, though I'd have to look that up and don't really have the time right now.

Anyway, I'm gonna close this out - we're actually probably going to be closing the github "Issues" tab altogether, since nobody really checks this at all, so questions like yours end up staying out here unanswered forever.  :)  If you wanted more help on any of this, feel free to stop by the Discord and ask!
