### ISSUE TITLE
[Request] Sell all non-favourite like in TPS

### ISSUE THREAD

**Issue by AvoidAtAllCosts** [BLCM/BLCMods#1042]
Is it possible to make a mod that allows the user to sell all items which are not marked as favourites with one button press? I personally prefer this system over the one used in BL2 in which you manually need to mark everything as trash.

**Comment by apocalyptech** [comment]
I'm not sure if that's something that'd be possible or not, but I'd recommend you stop in to the Discord and ask about it, if it's something you're still interested in.  I'm going to close this out over here, regardless, because we're shutting down this "Issues" section entirely.  As you've probably noticed, it's never been very well monitored.  You'll have much better luck at Discord!
