### ISSUE TITLE
Sorting mods

### ISSUE THREAD

**Issue by bugworm** [BLCM/BLCMods#388]
I think that getting mods that you want is a bit hard right now. Sorting files with author nicknames is mindless, because you can add someting like `Author: Bugworm` at the begining of the file(it's already the case for a lot of mods), and maybe some communication data, like mail, discord id etc. Also github is showing contributors, which is, in most cases, only author. I don't track mods community and mods in general, so you probably know better what categories should be there. My proposal is something like:

BLCMods
├── Borderlands 2 mods
│   ├── Balancing modes
│   │   └── patch.txt
│   ├── Game modes
│   │   └── pandemonium.txt
│   ├── Gear Replacement
│   │   ├── Balanced
│   │   │   ├── Class Mods
│   │   │   │   ├── Maya
│   │   │   │   │   └── mod.txt
│   │   │   │   └── Zer0
│   │   │   │       └── mod.txt
│   │   │   ├── Grenades
│   │   │   │   └── mod.txt
│   │   │   ├── Guns
│   │   │   │   ├── Pistols
│   │   │   │   │   ├── Jakobs
│   │   │   │   │   │   └── mod.txt
│   │   │   │   │   └── Maliwan
│   │   │   │   │       └── mod.txt
│   │   │   │   └── Sniper Rifles
│   │   │   │       ├── Jakobs
│   │   │   │       │   └── mod.txt
│   │   │   │       └── Maliwan
│   │   │   │           └── mod.txt
│   │   │   ├── Relics
│   │   │   │   └── mod.txt
│   │   │   └── Shields
│   │   │       ├── Anshin
│   │   │       │   └── mod.txt
│   │   │       └── Hyperion
│   │   │           └── mod.txt
│   │   └── Just4Fun
│   │       ├── Class Mods
│   │       │   ├── Maya
│   │       │   │   └── mod.txt
│   │       │   └── Zer0
│   │       │       └── mod.txt
│   │       ├── Grenades
│   │       │   └── mod.txt
│   │       ├── Guns
│   │       │   ├── Pistols
│   │       │   │   ├── Jakobs
│   │       │   │   │   └── mod.txt
│   │       │   │   └── Maliwan
│   │       │   │       └── mod.txt
│   │       │   └── Sniper Rifles
│   │       │       ├── Jakobs
│   │       │       │   └── mod.txt
│   │       │       └── Maliwan
│   │       │           └── mod.txt
│   │       ├── Relics
│   │       │   └── mod.txt
│   │       └── Shields
│   │           ├── Anshin
│   │           │   └── mod.txt
│   │           └── Hyperion
│   │               └── mod.txt
│   │   └── Skins
│   ├── Mics
│   │   └── mod.txt
│   └── Skills
│       ├── Maya
│       │   └── mod.txt
│       └── Zer0
│           └── mod.txt
└── Pre Sequel mods

**Comment by Ravenjim** [comment]
cant say i disagree but at the same time getting all the people to move their mods would be a bit of a pain
 imo

**Comment by bugworm** [comment]
This can be done without author's participation

**Comment by Ravenjim** [comment]
Ill bring that up in Shadows server since its there where the majority of modders are located

**Comment by Ravenjim** [comment]
Allright the general opinion is that a better sorting is in order.
there are talks of moving to a new site with better option such as tagging
But i am more of the idea to just Make the Hub work better.

For now what i am thinking of Doing is just make A folder Called Categories Where we will put EVERYTHING sorted and a folder Named Authors where everything will be as is now till everyone gets to understand the new system. 

There is still talk going on the issue as there is not a clear agreement yet.

**Comment by infamous27x** [comment]
I agree we should sort things out, this is my idea:

└── Guns
 └── Pistols
   └── Discipline          Made by **Aaron0000**
   └── Mercury            Made by **Soze**
   └── Irradiator           Made by **ItsCoolDood**
 └── Shotguns
  └── Punter               Made by **Aaron0000**
  └── Artemis              Made by **Soze**

└── Game changers
  └── Pandemonium      Made by **Aaron0000**
  └── Chaotic Teams       Made by **LightChaosMan**

└── Weapon Buffs / Changes
  └── Combat Overhaul     Made by **Orudeon**
   └── **Insert plenty of other mods from Orudeon here**
└── Skill Changes
  └── Zer0
   └── Singularity Unforeseen     Made by **empireScum**
   └── Slag Unforeseen               Made by **Soze**
 └── Gaige
   └── Gaige Buffs                        Made by **AngrierPat**
   └── Irrational Smasher             Made by **AngrierPat**
   └── Toggleable Deathtrap        Made by **Soze**

You get my point by now, basically not giving folders to people because this would clutter it in my opinion, we could rather CTRL + F and search the Authors name / file name to search for the specific mod you are looking for.

Also for the discussion that went on in the Discord Server, it was going to Nexus, but there's still a discussion going on saying if we should go. I personally disagree, we could make the GitHub way nicer sorting wise. It is time for a change, but going to another site isn't

**Comment by Ravenjim** [comment]
Ah see that was my idea as well to skip the modder name folder BUT think about light. if you search LIghtChaosMan there will be like ONLY mods that are like
"install with LightChaosMan Filter tool" thanks to LightChaosMan and he never appears. so i believe the Modder name folder AFTER category or subcategory alliviates that problem

**Comment by bugworm** [comment]
I've created a sorted branch, you can contribute to it.
https://github.com/BLCM/BLCMods/tree/sorted
Give me ideas about folders(all new folders is (S)Folder for now). I will also add readme and templates for contributing

**Comment by Ravenjim** [comment]
Ah dont worry about it imma get to it myself with what was "semi agreed" so far in the dc imma get on it tommorow. I think the best way would be ONE folder tho that has the rest inside.
Ill see what u did But if u dont mind let me for now handle that as it is a pretty delicate issue so far in the server.

**Comment by bugworm** [comment]
Copying my message from discord
hey guys, I was thinking about sorting mods, and... how about tags? We can just tag mods, like #weapons, so we can sort mods in separate file. Also we don't need to change file hierarсhy too much, just add a folder and README.md for each mod. This will also allow to have README.md per author, if he want to summarize his mods or stuff like that. Also it will be easier to search mods. And last thing - README.md should contain DOWNLOAD button, so people will search README file and download mod directly from there

I'll test it in forked repo later today

**Comment by Ravenjim** [comment]
Lets discuss this on DC will be fastert

**Comment by bugworm** [comment]
https://github.com/bugworm/Categories
