### ISSUE TITLE
BL2HexMultitool MaxLVL does not patch enemies

### ISSUE THREAD

**Issue by RolilithMordebricks** [BLCM/BLCMods#420]
Enemy levels and quests aren't scaling with the player after levels 72-75+

**Comment by c0dycode** [comment]
When did you download the tool? 
Only the newest version from 7 days ago has the patch that allows enemies and items to scale with your level.

**Comment by RolilithMordebricks** [comment]
I got it yesterday. Maybe someone gave me an outdated link

**Comment by c0dycode** [comment]
Was it this direct-link to my repo?
https://github.com/c0dycode/BL2ModStuff/blob/master/Hexediting/BL2%20Hex-Multitool.zip

If so, that shouldn't be an issue, since I simply replaced the old version.

**Comment by RolilithMordebricks** [comment]
Got it. Only thing is with this one is that the max is locked to 92. Hope this is temporary.

**Comment by c0dycode** [comment]
Yes, that's because the previous one didn't allow you to keep using OP-Levels and neither Items nor enemies were scaling. This one limits max lvl to 92 + 8 OP levels. So basically the same result.
When I increased it beyond 92, I've seen no more loot, vendors were always empty, game crashes when going back to menu and possibly more bugs I've missed.. So unless we find a way to remove that 100-Limit, not much I can do, sorry.

Glad you got it working though. Have fun with it :)

**Comment by Ravenjim** [comment]
Issue Resolved id suppose closing issue now.
