### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by vWolvenn** [BLCM/BLCMods#517]
Is there anyway to add something like moneyshot to a weapon/ or anything that triggers on the last shot of a gun

and can i change a partlocked gun ie making the greed always spawn non elemental?

**Comment by Greeem** [comment]
Yes. You need to modify the ElementalPartData.

**Comment by infamous27x** [comment]
There is, but you can only use behaviors that have Skills written in them ie: Evie, Grog Nozzle.
Writing skills isn't the easiest, but it may be worth. I don't exactly know how to make it trigger on the last shot only, since that is either a Behavior or a SkillConstraint.

Also @Greeem is wrong, it has NOTHING to do with the ElementalPartData.

**Comment by Greeem** [comment]
@infamous27x I was talking about the Greed being Non-Elemental.

As for the first one, I have no idea.

**Comment by Greeem** [comment]
I should have been clearer when responding to you. @vWolvenn I don't even know where to begin with skills! Listen to soze, he's smart.
