### ISSUE TITLE
Changing a characters base stats (melee, health, reload speed)

### ISSUE THREAD

**Issue by NoahKr** [BLCM/BLCMods#738]
I've been having trouble changing a specific character's base stats. For instance changing the base melee damage modifier for all characters is no problem. But I can't seem to figure out how I would go about only changing a specific character's melee damage (zer0 for instance).

Any help would be appreciated.
Thanks in advance.

**Comment by NoahKr** [comment]
Can I ask why this was closed? My issue hasn't been resolved.

**Comment by Ethel173** [comment]
sorry, my apologies, its just been quite a while since this was opened and i had assumed you already received an answer via a pm or discord message and forgot to close it yourself.

as for changing a VH's stats, its not possible to directly change attributes only for a certain character _directly_, however it ___is___ possible to add attribute modifiers to skills, one of which being the action skill which is essentially required to pick up and unique to that character, using this you can create a pseudo changed attribute by attaching modifiers to this base skill.

ex: adding +SMG dmg to maya's phaselock skill, or +melee dmg to zeros deception skill

**Comment by NoahKr** [comment]
Thanks for your answer :)

**Comment by NoahKr** [comment]
@Ethel173 Hey I just wanted to let you know that your proposed pseudo base modifier doesn't work, because all modified attributes on an action skilsl are only applied when the action skill is active,

I eventually decided on adding the base damage to execute. Cheers.
