### ISSUE TITLE
Need Some Help (Close)

### ISSUE THREAD

**Issue by vWolvenn** [BLCM/BLCMods#775]
So this is something that's fairly simple however I can't seem to make it work. How could I change the rarity of a pearlescent to legendary, I've managed to get limescent and red rarity but no luck with legendary. Any help would be appreciated.

**Comment by infamous27x** [comment]
`set barrel/body rarity (BaseValueConstant=6.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)`

Not sure which value you should use, but try - values if it doesn't work, pearls are generally iffy in rarities though, make sure you also check out the body of the pearl, because some have a custom body.

**Comment by vWolvenn** [comment]
tried messing with it more, ive hit seraph and purple but no luck with legendary. If anyone can  help that would be appreciated v much
