### ISSUE TITLE
[Request] Have Embrace the Pain affect thrown buzz axe

### ISSUE THREAD

**Issue by studdugie** [BLCM/BLCMods#928]
Hello,

First off, thank you all for the UCP and the other mods. You all have done an incredible job and I'm grateful. The UCP has brought me back to the Borderlands after 3+ years away and I am having a lot of fun tweaking builds and load outs to accommodate the changes. Which brings me to my request.

Embrace the Pain in Krieg's Mania tree increases fire rate when shields are down. Unfortunately, it does not apply to the rate at which Krieg's buzz axe can be thrown. I think it's a bug or at least something that should be addressed, assuming it's possible, because wearing COMs that affect fire rate does increase the buzz axe throw rate. So whether that disconnect was intentional or a bug on GBX's part I think it would be great if you could address it. In terms of its effect on game play, I think it would improve the utility of Buzz Axe Rampage when fighting bosses because it can increase Krieg's DPS by allowing Krieg to more effectively engage bosses at range.

Thanks!

**Comment by apocalyptech** [comment]
Hello!  If this is something you're still interested in, I'd recommend stopping by the Discord and asking about it there.  We're closing out this whole Issues section because (as you've no doubt noticed), it was never terribly well monitored, and questions like yours could sit out here for months, never getting an answer.  So yeah, stop by the Discord!  Closing this one out, on here.
