### ISSUE TITLE
FromDarkHell Weapon Randomizer

### ISSUE THREAD

**Issue by Dragonscale1234** [BLCM/BLCMods#984]
Every time I try to get the weapon randomizer to work on the filter tool the tool crashes and gives me an error log. Could someone please help me?
[log-1528895925600.txt](https://github.com/BLCM/BLCMods/files/2098239/log-1528895925600.txt)

**Comment by FromDarkHell** [comment]
As taken from the FAQ (https://docs.google.com/document/d/17bwfQXWavBDiQuthxueXbRzB7LIx37Ki1a4-P-0qBW8/):

Is your filtertool having issues merging large mods (think, randomizers), and crashing at some point, but otherwise working fine?
Odds are your operating system is not giving java enough RAM to work with. If this is the case, the log files should mention something about heapspace.
To fix this, run the filtertool using cmd, using any of these three commands, which try to allocate more & more RAM to java.

java -XX:MaxHeapFreeRatio=50 -Xmx1g -jar FilterTool.jar
java -XX:MaxHeapFreeRatio=50 -Xmx1536m -jar FilterTool.jar
java -XX:MaxHeapFreeRatio=50 -Xmx2g -jar FilterTool.jar

Try using the first and go down when the first doesn't work.
